SET SERVEROUTPUT ON
SET VERIFY OFF 

ACCEPT CODE NUMBER PROMPT "Entrer le code du produit : "

DECLARE
	valcode COMPAGNIE.NACCPRODUITS.CODE%TYPE:= '&CODE'; 
	code_existe COMPAGNIE.NACCPRODUITS.CODE%TYPE;

BEGIN
	SELECT CODE INTO  code_existe FROM COMPAGNIE.NACCPRODUITS WHERE UPPER(CODE)= UPPER(valcode);
	--Insertion des bixi dans la table NACCPRODUITS supprimes	 avant de les supprimer
	INSERT INTO COMPAGNIE.PRODUITS_SUPPRIMEES SELECT * FROM COMPAGNIE.NACCPRODUITS WHERE UPPER(CODE)= UPPER(valcode);
	--Suppression de la NACCPRODUITS
	DELETE FROM COMPAGNIE.NACCPRODUITS WHERE UPPER(CODE)= UPPER(valcode);
	DBMS_OUTPUT.PUT_LINE('Le Produit est supprimee');
	COMMIT;

	COMPAGNIE.affiche_produits();
	
EXCEPTION

	WHEN no_data_found THEN
		DBMS_OUTPUT.PUT_LINE('Le CODE n''existe pas');

END;
/
SET VERIFY ON




