SET SERVEROUTPUT ON
SET VERIFY OFF 

ACCEPT NOFOUR NUMBER PROMPT "Entrer le NOFOUR du founisseur : "

DECLARE
	valnofour COMPAGNIE.NACCFOURNISSEURS.NOFOUR%TYPE:= '&NOFOUR'; 
	nofour_existe COMPAGNIE.NACCFOURNISSEURS.NOFOUR%TYPE;

BEGIN
	SELECT NOFOUR INTO  nofour_existe FROM COMPAGNIE.NACCFOURNISSEURS WHERE UPPER(NOFOUR)= UPPER(valnofour);
	--Insertion des bixi dans la table NACCFOURNISSEURS supprimes	 avant de les supprimer
	INSERT INTO COMPAGNIE.FOURNISSEURS_SUPPRIMEES SELECT * FROM COMPAGNIE.NACCFOURNISSEURS WHERE UPPER(NOFOUR)= UPPER(valnofour);
	--Suppression de la NACCFOURNISSEURS
	DELETE FROM COMPAGNIE.NACCFOURNISSEURS WHERE UPPER(NOFOUR)= UPPER(valnofour);
	DBMS_OUTPUT.PUT_LINE('Le NOFOUR est supprimee');
	COMMIT;

	COMPAGNIE.affiche_fournisseurs();

EXCEPTION

	WHEN no_data_found THEN
		DBMS_OUTPUT.PUT_LINE('Le NOFOUR n''existe pas');

END;
/
SET VERIFY ON


