SET SERVEROUTPUT ON
CREATE OR REPLACE TRIGGER trigger_fournisseir
AFTER UPDATE OF NOFOUR ON COMPAGNIE.NACCFOURNISSEURS
FOR EACH ROW
BEGIN
    DBMS_OUTPUT.PUT_LINE('Modification en cascade de : ' ||:NEW.NOFOUR);
    update COMPAGNIE.NACCFOURNISSEURS set NOFOUR=:NEW.NOFOUR where NOFOUR=:OLD.NOFOUR;
 END;
/

--create view vue_NACCFOURNISSEURS as select * from COMPAGNIE.NACCFOURNISSEURS;

--insert into COMPAGNIE.NACCFOURNISSEURS values(...);