SET SERVEROUTPUT ON
SET VERIFY OFF 

ACCEPT NOFOUR NUMBER PROMPT "Entrer le NOFOUR du founisseur : "
ACCEPT newNOFOUR NUMBER PROMPT "Entrer le nouveau NOFOUR du founisseur : "

DECLARE
	valnofour COMPAGNIE.NACCFOURNISSEURS.NOFOUR%TYPE:= '&NOFOUR'; 
	varNEWnofour COMPAGNIE.NACCFOURNISSEURS.NOFOUR%TYPE:= '&newNOFOUR'; 
	nofour_existe COMPAGNIE.NACCFOURNISSEURS.NOFOUR%TYPE;

BEGIN

/*
	SELECT NOFOUR INTO  nofour_existe FROM COMPAGNIE.NACCFOURNISSEURS WHERE UPPER(NOFOUR)= UPPER(valnofour);
	--Insertion des bixi dans la table NACCFOURNISSEURS supprimes	 avant de les supprimer
	UPDATE FROM COMPAGNIE.NACCFOURNISSEURS WHERE UPPER(NOFOUR)= UPPER(valnofour);
	*/
	
	 UPDATE COMPAGNIE.NACCFOURNISSEURS SET NOFOUR = varNEWnofour WHERE NOFOUR = valnofour;
	DBMS_OUTPUT.PUT_LINE('Le NOFOUR a ete mis a jour ');
	COMMIT;

	COMPAGNIE.affiche_fournisseurs();
	COMPAGNIE.affiche_produits();

EXCEPTION

	WHEN no_data_found THEN
		DBMS_OUTPUT.PUT_LINE('Le NOFOUR n''existe pas');
		DBMS_OUTPUT.PUT_LINE('Liste des fournisseurs');
		COMPAGNIE.affiche_fournisseurs();

END;
/
SET VERIFY ON

 
 /*
 UPDATE COMPAGNIE.NACCFOURNISSEURS SET NOFOUR = 55 WHERE NOFOUR = 12;
 select * from compagnie.naccproduits;

*/

/*
SET SERVEROUTPUT ON
SET VERIFY OFF 


ACCEPT NOFOUR NUMBER PROMPT "Entrer le NOFOUR du founisseur : "

DECLARE
	valnofour COMPAGNIE.NACCFOURNISSEURS.NOFOUR%TYPE:= '&NOFOUR'; 
	nofour_existe COMPAGNIE.NACCFOURNISSEURS.NOFOUR%TYPE;

BEGIN
	SELECT NOFOUR INTO  nofour_existe FROM COMPAGNIE.NACCFOURNISSEURS WHERE UPPER(NOFOUR)= UPPER(valnofour);
	--Suppression de la NACCFOURNISSEURS
	DELETE FROM COMPAGNIE.NACCFOURNISSEURS WHERE UPPER(NOFOUR)= UPPER(valnofour);
	DBMS_OUTPUT.PUT_LINE('Le NOFOUR est supprimee');
	COMMIT;

	COMPAGNIE.affiche_fournisseurs();

EXCEPTION

	WHEN no_data_found THEN
		DBMS_OUTPUT.PUT_LINE('Le NOFOUR n''existe pas');

END;
/
SET VERIFY ON



*/